import type { AppCharacter, DefaultAppCharacter } from "@Src/types";
import { EModAffect } from "@Src/constants";
import { applyModifier, makeModApplier } from "@Src/utils/calculation";
import { EModSrc } from "../constants";
import { checkAscs, checkCons, genExclusiveBuff } from "../utils";

const Alhaitham: DefaultAppCharacter = {
  code: 65,
  name: "Alhaitham",
  icon: "2/2c/Alhaitham_Icon",
  sideIcon: "c/cb/Alhaitham_Side_Icon",
  rarity: 5,
  nation: "sumeru",
  vision: "dendro",
  weaponType: "sword",
  EBcost: 70,
  talentLvBonusAtCons: {
    ES: 3,
    EB: 5,
  },
  innateBuffs: [
    {
      src: EModSrc.A4,
      description: `Each point of Alhaitham's Elemental Mastery will increase the {Projection Attacks DMG}#[gr] [~ES]
      and Particular Field: Fetters of Phenomena {[EB] DMG}#[gr] by {0.1%}#[b,gr]. Max {100%}#[r].`,
      isGranted: checkAscs[4],
      applyFinalBuff: ({ totalAttr, attPattBonus, calcItemBuffs, desc, tracker }) => {
        const buffValue = Math.min(totalAttr.em * 0.1, 100);
        applyModifier(desc, attPattBonus, "EB.pct_", buffValue, tracker);
        calcItemBuffs.push(genExclusiveBuff(EModSrc.A4, "ES.0", "pct_", buffValue));
      },
    },
  ],
  buffs: [
    {
      index: 0,
      src: "Chisel-Light Mirrors",
      affect: EModAffect.SELF,
      description: `When he possesses Chisel-Light Mirrors, Alhaitham gains {Dendro Infusion}#[dendro].`,
      infuseConfig: {
        overwritable: false,
      },
    },
    {
      index: 2,
      src: EModSrc.C2,
      affect: EModAffect.SELF,
      description: `When Alhaitham generates a Chisel-Light Mirror, his {Elemental Mastery}#[gr] will be increased by
      {50}#[b,gr] for 8 seconds, max {4}#[r] stacks.`,
      isGranted: checkCons[2],
      inputConfigs: [
        {
          type: "stacks",
          max: 4,
        },
      ],
      applyBuff: ({ totalAttr, inputs, desc, tracker }) => {
        applyModifier(desc, totalAttr, "em", (inputs[0] || 0) * 50, tracker);
      },
    },
    {
      index: 3,
      src: EModSrc.C4,
      affect: EModAffect.PARTY,
      description: `Based on the number of Chisel-Light Mirrors consumed and generated by Particular Field: Fetters of
      Phenomena [EB]:
      <br />• Each Mirror consumed will increase the {Elemental Mastery}#[gr] of all other nearby party members by
      {30}#[b,gr] for 15s.
      <br />• Each Mirror generated will grant Alhaitham a {10%}#[b,gr] {Dendro DMG Bonus}#[gr] for 15s.`,
      isGranted: checkCons[4],
      inputConfigs: [
        {
          label: "Consumed Mirrors",
          type: "select",
          initialValue: 0,
          max: 3,
        },
      ],
      applyBuff: ({ fromSelf, totalAttr, inputs, desc, tracker }) => {
        const stacks = inputs[0] || 0;

        if (fromSelf) {
          applyModifier(desc, totalAttr, "dendro", (3 - stacks) * 10, tracker);
        } else {
          applyModifier(desc, totalAttr, "em", stacks * 30, tracker);
        }
      },
    },
    {
      index: 4,
      src: EModSrc.C6,
      affect: EModAffect.SELF,
      description: `If Alhaitham generates Chisel-Light Mirrors when their numbers have already maxed out, his
      {CRIT Rate}#[gr] and {CRIT DMG}#[gr] will increase by {10%}#[b,gr] and {70%}#[b,gr] respectively for 6s.`,
      isGranted: checkCons[6],
      applyBuff: makeModApplier("totalAttr", ["cRate_", "cDmg_"], [10, 70]),
    },
  ],
};

export default Alhaitham as AppCharacter;
