import type { DataCharacter } from "@Src/types";
import { Green } from "@Components/atoms";
import { EModAffect } from "@Src/constants";
import { EModSrc, MEDIUM_PAs } from "../constants";
import { applyPercent } from "@Src/utils";
import { applyModifier, makeModApplier } from "@Calculators/utils";
import { checkAscs, checkCons, talentBuff } from "../utils";

import laylaImg from "@Src/assets/images/layla.png";

const Layla: DataCharacter = {
  code: 61,
  beta: true,
  name: "Layla",
  icon: laylaImg,
  sideIcon: "",
  rarity: 4,
  nation: "sumeru",
  vision: "cryo",
  weaponType: "sword",
  stats: [
    [930, 18, 55],
    [2389, 47, 141],
    [3084, 60, 182],
    [4619, 90, 273],
    [5113, 100, 302],
    [5881, 115, 347],
    [6540, 128, 386],
    [7308, 143, 432],
    [7801, 152, 461],
    [8569, 167, 506],
    [9062, 177, 535],
    [9831, 192, 581],
    [10324, 202, 610],
    [11092, 217, 655],
  ],
  bonusStat: { type: "hp_", value: 6 },
  NAsConfig: {
    name: "Sword of the Radiant Path",
  },
  activeTalents: {
    NA: {
      stats: [
        { name: "1-Hit", multBase: 51.2 },
        { name: "2-Hit", multBase: 48.5 },
        { name: "3-Hit", multBase: 73 },
      ],
    },
    CA: { stats: [{ name: "Charged Attack DMG", multBase: [47.7, 52.5] }] },
    PA: { stats: MEDIUM_PAs },
    ES: {
      name: "Nights of Formal Focus",
      image: "",
      xtraLvAtCons: 3,
      stats: [
        { name: "Skill DMG", multBase: 14.85 },
        {
          name: "Shooting Star DMG",
          multBase: 17.1,
          getTalentBuff: ({ char, totalAttr }) => {
            return talentBuff(
              [checkAscs[4](char), "flat", [true, 4], applyPercent(totalAttr.hp, 1.5)],
              [checkCons[6](char), "pct", [false, 6], 40]
            );
          },
        },
        {
          name: "Base Shield DMG Absorption",
          notAttack: "shield",
          baseStatType: "hp",
          multBase: 10.8,
          multType: 2,
          flat: { base: 1040, type: 3 },
          getTalentBuff: ({ char }) => talentBuff([checkCons[1](char), "pct", [false, 1], 20]),
        },
      ],
      // getExtraStats: (lv) => [{ name: "Shield Duration", value: "12s" }],
    },
    EB: {
      name: "Dream of the Star-Stream Shaker",
      image: "",
      xtraLvAtCons: 5,
      stats: [{ name: "Starlight Slug DMG", baseStatType: "hp", multBase: 7 }],
      // getExtraStats: () => [
      //   { name: "Duration", value: "12s" },
      //   { name: "CD", value: "15s" },
      // ],
      energyCost: 60,
    },
  },
  passiveTalents: [
    {
      name: "Like Nascent Light",
      image: "",
      desc: (
        <>
          While the Curtain of Slumber is active, the Deep Sleep effect will activate each time the
          Curtain gains a Night Star:
          <br />• The <Green>Shield Strength</Green> of a character under the effect of the Curtain
          of Slumber increases by <Green b>6%</Green>.
          <br />• This effect can have a maximum of <Green b>4</Green> <Green>stacks</Green> and
          persists until the Curtain of Slumber disappears.
        </>
      ),
    },
    {
      name: "Sweet Slumber Undisturbed",
      image: "",
      desc: (
        <>
          The <Green>DMG</Green> dealt by the <Green>Shooting Stars</Green> fired by Nights of
          Formal Focus is increased by <Green b>1.5%</Green> of Layla's <Green>Max HP</Green>.
        </>
      ),
    },
    {
      name: "Talent for Daily Life",
      image: "",
      desc: <></>,
    },
  ],
  constellation: [
    {
      name: "Fortress of Fantasy",
      image: "",
      get desc() {
        return (
          <>
            {this.xtraDesc![0]}
            <br />
            Additionally, when unleashing Nights of Formal Focus, she will generate a shield for any
            nearby party members who are not being protected by a Curtain of Slumber. This shield
            will have 35% of the absorption of a Curtain of Slumber, will last for 12s, and will
            absorb Cryo DMG with 250% effectiveness.
          </>
        );
      },
      xtraDesc: [
        <>
          The <Green>Shield Absorption</Green> of the Curtain of Slumber generated by Nights of
          Formal Focus is increased by <Green b>20%</Green>.
        </>,
      ],
    },
    {
      name: "Light's Remit",
      image: "",
      desc: (
        <>
          When Shooting Stars from Nights of Formal Focus strike opponents, they will each restore{" "}
          <Green>1</Green> <Green>Energy</Green> to Layla. Each Shooting Star can restore Energy to
          her in this manner once.
        </>
      ),
    },
    { name: "Secrets of the Night", image: "" },
    {
      name: "Starry Illumination",
      image: "",
      get desc() {
        return (
          <>
            {this.xtraDesc![0]}
            <br />
            Open Mind can last up to 3s and will be removed 0.1s after dealing Normal or Charged
            Attack DMG.
          </>
        );
      },
      xtraDesc: [
        <>
          When Nights of Formal Focus starts to fire off Shooting Stars, it will grant all nearby
          party members the Open Mind effect, causing their{" "}
          <Green>Normal and Charged Attack DMG</Green> to increase based on <Green b>5%</Green> of
          Layla's <Green>Max HP</Green>.
        </>,
      ],
    },
    { name: "Stream of Consciousness", image: "" },
    {
      name: "Radiant Soulfire",
      image: "",
      get desc() {
        return (
          <>
            {this.xtraDesc![0]}
            <br />
            Additionally, the interval between the creation of Night Stars via Nights of Formal
            Focus is decreased by 20%.
          </>
        );
      },
      xtraDesc: [
        <>
          <Green>Shooting Stars</Green> from Nights of Formal Focus deal <Green b>40%</Green>{" "}
          <Green>increased DMG</Green>, and <Green>Starlight Slugs</Green> from Dream of the
          Star-Stream Shaker deal <Green b>40%</Green> <Green>increased DMG</Green>.
        </>,
      ],
    },
  ],
  innateBuffs: [
    {
      src: EModSrc.A4,
      desc: () => Layla.passiveTalents[1].desc,
      isGranted: checkAscs[4],
    },
    {
      src: EModSrc.C1,
      desc: () => Layla.constellation[0].xtraDesc![0],
      isGranted: checkCons[1],
    },
    {
      src: EModSrc.C6,
      desc: () => Layla.constellation[5].xtraDesc![0],
      isGranted: checkCons[6],
      applyBuff: makeModApplier("attPattBonus", "EB.pct", 40),
    },
  ],
  buffs: [
    {
      index: 0,
      src: EModSrc.A1,
      desc: () => Layla.passiveTalents[0].desc,
      isGranted: checkAscs[1],
      affect: EModAffect.ACTIVE_UNIT,
      inputConfigs: [
        {
          type: "stacks",
          max: 4,
        },
      ],
      applyBuff: ({ totalAttr, inputs, desc, tracker }) => {
        applyModifier(desc, totalAttr, "shStr", 6 * (inputs[0] || 0), tracker);
      },
    },
    {
      index: 3,
      src: EModSrc.C4,
      desc: () => Layla.constellation[3].xtraDesc![0],
      isGranted: checkCons[4],
      affect: EModAffect.PARTY,
      inputConfigs: [
        {
          label: "Max HP",
          type: "text",
          max: 99999,
          for: "teammate",
        },
      ],
      applyFinalBuff: ({ toSelf, totalAttr, attPattBonus, inputs, desc, tracker }) => {
        const maxHP = toSelf ? totalAttr.hp : inputs[0] || 0;
        const buffValue = applyPercent(maxHP, 5);
        applyModifier(desc, attPattBonus, ["NA.flat", "CA.flat"], buffValue, tracker);
      },
    },
  ],
};

export default Layla;
