import type { AppCharacter, DefaultAppCharacter } from "@Src/types";
import { EModAffect } from "@Src/constants";
import { applyModifier, makeModApplier } from "@Src/utils/calculation";
import { EModSrc, MEDIUM_PAs } from "../constants";
import { checkAscs, checkCons, exclBuff } from "../utils";

const Alhaitham: DefaultAppCharacter = {
  code: 65,
  name: "Alhaitham",
  icon: "2/2c/Alhaitham_Icon",
  sideIcon: "c/cb/Alhaitham_Side_Icon",
  rarity: 5,
  nation: "sumeru",
  vision: "dendro",
  weaponType: "sword",
  EBcost: 70,
  talentLvBonusAtCons: {
    ES: 3,
    EB: 5,
  },
  stats: [
    [1039, 24, 61],
    [2695, 63, 158],
    [3586, 84, 210],
    [5366, 126, 314],
    [5999, 141, 351],
    [6902, 162, 404],
    [7747, 182, 454],
    [8659, 203, 507],
    [9292, 218, 544],
    [10213, 240, 598],
    [10846, 255, 635],
    [11777, 276, 690],
    [12410, 291, 727],
    [13348, 313, 782],
  ],
  bonusStat: { type: "dendro", value: 7.2 },
  activeTalents: {
    NAs: {
      name: "Abductive Reasoning",
    },
    ES: {
      name: "Universality: An Elaboration on Form",
      image: "2/29/Talent_Universality_An_Elaboration_on_Form",
    },
    EB: {
      name: "Particular Field: Fetters of Phenomena",
      image: "0/08/Talent_Particular_Field_Fetters_of_Phenomena",
    },
  },
  calcList: {
    NA: [
      { name: "1-Hit", multFactors: 49.53 },
      { name: "2-Hit", multFactors: 50.75 },
      { name: "3-Hit (1/2)", multFactors: 34.18 },
      { name: "4-Hit", multFactors: 66.77 },
      { name: "5-Hit", multFactors: 83.85 },
    ],
    CA: [{ name: "Charged Attack (1/2)", multFactors: 55.26 }],
    PA: MEDIUM_PAs,
    ES: [
      {
        name: "Rush Attack DMG",
        multFactors: [
          { root: 193.6, attributeType: "atk" },
          { root: 154.88, attributeType: "em" },
        ],
        multFactorsAreOne: true,
      },
      {
        id: "ES.0",
        name: "Mirror Projection DMG",
        multFactors: [
          { root: 67.2, attributeType: "atk" },
          { root: 134.4, attributeType: "em" },
        ],
        multFactorsAreOne: true,
      },
    ],
    EB: [
      {
        name: "Single-Instance DMG",
        multFactors: [
          { root: 121.6, attributeType: "atk" },
          { root: 97.28, attributeType: "em" },
        ],
        multFactorsAreOne: true,
      },
    ],
  },
  passiveTalents: [
    {
      name: "Four-Causal Correction",
      image: "3/32/Talent_Four-Causal_Correction",
    },
    { name: "Mysteries Laid Bare", image: "f/f4/Talent_Mysteries_Laid_Bare" },
    {
      name: "Law of Reductive Overdetermination",
      image: "a/a4/Talent_Law_of_Reductive_Overdetermination",
    },
  ],
  constellation: [
    { name: "Intuition", image: "c/c9/Constellation_Intuition" },
    { name: "Debate", image: "9/9d/Constellation_Debate" },
    { name: "Negation", image: "4/4f/Constellation_Negation" },
    { name: "Elucidation", image: "b/b5/Constellation_Elucidation" },
    { name: "Sagacity", image: "c/c0/Constellation_Sagacity" },
    { name: "Structuration", image: "5/55/Constellation_Structuration" },
  ],
  innateBuffs: [
    {
      src: EModSrc.A4,
      description: `Each point of Alhaitham's Elemental Mastery will increase the {Projection Attacks DMG}#[gr] [~ES]
      and Particular Field: Fetters of Phenomena {[EB] DMG}#[gr] by {0.1%}#[b,gr]. Max {100%}#[r].`,
      isGranted: checkAscs[4],
      applyFinalBuff: ({ totalAttr, attPattBonus, calcItemBuffs, desc, tracker }) => {
        const buffValue = Math.min(totalAttr.em * 0.1, 100);
        applyModifier(desc, attPattBonus, "EB.pct_", buffValue, tracker);
        calcItemBuffs.push(exclBuff(EModSrc.A4, "ES.0", "pct_", buffValue));
      },
    },
  ],
  buffs: [
    {
      index: 0,
      src: "Chisel-Light Mirrors",
      affect: EModAffect.SELF,
      description: `When he possesses Chisel-Light Mirrors, Alhaitham gains {Dendro Infusion}#[dendro].`,
      infuseConfig: {
        overwritable: false,
      },
    },
    {
      index: 2,
      src: EModSrc.C2,
      affect: EModAffect.SELF,
      description: `When Alhaitham generates a Chisel-Light Mirror, his {Elemental Mastery}#[gr] will be increased by
      {50}#[b,gr] for 8 seconds, max {4}#[r] stacks.`,
      isGranted: checkCons[2],
      inputConfigs: [
        {
          type: "stacks",
          max: 4,
        },
      ],
      applyBuff: ({ totalAttr, inputs, desc, tracker }) => {
        applyModifier(desc, totalAttr, "em", (inputs[0] || 0) * 50, tracker);
      },
    },
    {
      index: 3,
      src: EModSrc.C4,
      affect: EModAffect.PARTY,
      description: `Buff based on the number of Chisel-Light Mirrors consumed and generated by Particular Field: Fetters
      of Phenomena [EB]:
      <br />• Each Mirror consumed will increase the {Elemental Mastery}#[gr] of all other nearby party members by
      {30}#[b,gr] for 15s.
      <br />• Each Mirror generated will grant Alhaitham a {10%}#[b,gr] {Dendro DMG Bonus}#[gr] for 15s.`,
      isGranted: checkCons[4],
      inputConfigs: [
        {
          label: "Consumed Mirrors",
          type: "select",
          initialValue: 0,
          max: 3,
        },
      ],
      applyBuff: ({ toSelf, totalAttr, inputs, desc, tracker }) => {
        const stacks = inputs[0] || 0;

        if (toSelf) {
          applyModifier(desc, totalAttr, "dendro", (3 - stacks) * 10, tracker);
        } else {
          applyModifier(desc, totalAttr, "em", stacks * 30, tracker);
        }
      },
    },
    {
      index: 4,
      src: EModSrc.C6,
      affect: EModAffect.SELF,
      description: `If Alhaitham generates Chisel-Light Mirrors when their numbers have already maxed out, his
      {CRIT Rate}#[gr] and {CRIT DMG}#[gr] will increase by {10%}#[b,gr] and {70%}#[b,gr] respectively for 6s.`,
      isGranted: checkCons[6],
      applyBuff: makeModApplier("totalAttr", ["cRate_", "cDmg_"], [10, 70]),
    },
  ],
};

export default Alhaitham as AppCharacter;
