export const mapVerson3_0: Record<string, string> = {
  HP: "hp",
  ATK: "atk",
  DEF: "def",
  "HP%": "hp_",
  "ATK%": "atk_",
  "DEF%": "def_",
  "Elemental Mastery": "em",
  "CRIT Rate": "cRate",
  "CRIT DMG": "cDmg",
  "Energy Recharge": "er",
  "Pyro DMG Bonus": "pyro",
  "Hydro DMG Bonus": "hydro",
  "Electro DMG Bonus": "electro",
  "Cryo DMG Bonus": "cryo",
  "Geo DMG Bonus": "geo",
  "Anemo DMG Bonus": "anemo",
  "Dendro DMG Bonus": "dendro",
  "Physical DMG Bonus": "phys",
  "Healing Bonus": "healBn",
  //
  "Normal Attack": "NA",
  "Charged Attack": "CA",
  "Plunging Attack": "PA",
  "Elemental Skill": "ES",
  "Elemental Burst": "EB",
  //
  Vaporize: "vaporize",
  Melt: "melt",
  Hyperbloom: "hyperbloom",
  Burgeon: "burgeon",
  Burning: "burning",
  Shattered: "shattered",
  Overloaded: "overloaded",
  "Electro-Charged": "electroCharged",
  Swirl: "swirl",
  Superconduct: "superconduct",
  Bloom: "bloom",
  spread: "spread",
  aggravate: "aggravate",
  //
  "Fervent Flames": "pyro",
  "Shattering Ice": "cryo",
  "Enduring Rock": "geo",
  "Soothing Water": "hydro",
  "Sprawling Greenery": "dendro",
  //
  "DEF reduction": "def",
  "Pyro RES reduction": "pyro",
  "Hydro RES reduction": "hydro",
  "Cryo RES reduction": "cryo",
  "Electro RES reduction": "electro",
  "Anemo RES reduction": "anemo",
  "Geo RES reduction": "geo",
  "Dendro RES reduction": "dendro",
};

export const mapGoodFormat: Record<string, string> = {
  atk: "atk",
  atk_: "atk_",
  hp: "hp",
  hp_: "hp_",
  def: "def",
  def_: "def_",
  eleMas: "em",
  enerRech_: "er",
  critRate_: "cRate",
  critDMG_: "cDmg",
  heal_: "healBn",
  pyro_dmg_: "pyro_",
  hydro_dmg_: "hydro_",
  electro_dmg_: "electro_",
  geo_dmg_: "geo_",
  anemo_dmg_: "anemo_",
  dendro_dmg_: "dendro_",
  cryo_dmg_: "cryo_",
  physical_dmg_: "phys_",
};
